version: '2'
services:
  webserver:
    build:
      context: ./.docker/nginx-php
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - volumes_source
    volumes:
      - ./storage/logs/nginx/:/var/log/nginx
      - ./config/sites/:/etc/nginx/sites-enabled/
  mysql:
    image: mysql:5.6
    volumes_from:
      - volumes_data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  redis:
      image: redis:3.0
      volumes_from:
          - volumes_data
      ports:
          - "6379:6379"

  playground:
    build:
      context: ./.docker/playground
    volumes_from:
      - volumes_source
    tty: true

  volumes_source:
      image: tianon/true
      volumes:
          - $PROJECT_ROOT:/var/www

  volumes_data:
    image: tianon/true
    volumes:
      - ./storage/data/mysql:/var/lib/mysql
      - ./storage/data/redis:/data
